; version.asm
;
; Auto-generated by ZXVersion.exe
; On 06 Feb 2020 at 12:27

BuildNo                 macro()
                        db "1"
mend

BuildNoValue            equ "1"
BuildNoWidth            equ 0 + FW1



BuildDate               macro()
                        db "06 Feb 2020"
mend

BuildDateValue          equ "06 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW6 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "12:27"
mend

BuildTimeValue          equ "12:27"
BuildTimeWidth          equ 0 + FW1 + FW2 + FWColon + FW2 + FW7



BuildTimeSecs           macro()
                        db "12:27:23"
mend

BuildTimeSecsValue      equ "12:27:23"
BuildTimeSecsWidth      equ 0 + FW1 + FW2 + FWColon + FW2 + FW7 + FWColon + FW2 + FW3
