; version.asm
;
; Auto-generated by ZXVersion.exe
; On 09 Feb 2020 at 09:11

BuildNo                 macro()
                        db "3"
mend

BuildNoValue            equ "3"
BuildNoWidth            equ 0 + FW3



BuildDate               macro()
                        db "09 Feb 2020"
mend

BuildDateValue          equ "09 Feb 2020"
BuildDateWidth          equ 0 + FW0 + FW9 + FWSpace + FWF + FWe + FWb + FWSpace + FW2 + FW0 + FW2 + FW0



BuildTime               macro()
                        db "09:11"
mend

BuildTimeValue          equ "09:11"
BuildTimeWidth          equ 0 + FW0 + FW9 + FWColon + FW1 + FW1



BuildTimeSecs           macro()
                        db "09:11:12"
mend

BuildTimeSecsValue      equ "09:11:12"
BuildTimeSecsWidth      equ 0 + FW0 + FW9 + FWColon + FW1 + FW1 + FWColon + FW1 + FW2
